### ISSUE TITLE
Compilation error for Android x86

### ISSUE THREAD

**Issue by inactive123** [libretro/libretro-meowPC98#19]
See this log -

http://p.0bl.net/59950

**Comment by r-type** [comment]
can't try , but maybe you can to do something like what we have done for win32 built
https://github.com/libretro/libretro-meowPC98/blob/master/libretro/compiler.h#L28
i mean define those for X86 Android compilation
```
#define	sigsetjmp(env, mask)	setjmp(env)
#define	siglongjmp(env, val)	longjmp(env, val)
```
But no sure how to handle specific define only for ANDROIDX86
maybe 
```
#if defined( __i386__) && defined(__ANDROID__)
#define	sigsetjmp(env, mask)	setjmp(env)
#define	siglongjmp(env, val)	longjmp(env, val)
#endif 
```
in complier.h
